# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12
language: objective-c

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -project StringSearchKit.xcodeproj -scheme StringSearchKit -sdk macosx10.15 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
